### PR TITLE
fix(toM3u8): set label for vttPlaylist from label instead of lang

### PR DESCRIPTION
**Pull request by RomeroDiver**
Fix the issue when the subtitles' `label` property was set from lang instead of label

### CODE REVIEW

**Comment by gkatsev** [comment]
I believe this isn't the spec-compliant way of labeling text tracks. The expected way is with a Label element.
Also see answer here https://github.com/videojs/mpd-parser/pull/153#issuecomment-971757739

there's some direction on how to do it with a label element here https://github.com/videojs/video.js/issues/6960#issuecomment-733115810

**Comment by RomeroDiver** [comment]
I agree with your comment, however this fix is exactly to make the Label element work. E.g. without the fix the following is not working properly - the Label element is not read,
```
<AdaptationSet mimeType="text/vtt" lang="en">
      <Role schemeIdUri="urn:mpeg:dash:role" value="subtitle"/>
      <Label>English</Label>
      <Representation id="12" bandwidth="256">
        <BaseURL>url</BaseURL>
      </Representation>
    </AdaptationSet>
```

**Comment by RomeroDiver** [comment]
> 

What do you think? I think this change is according to the specs

**Comment by gkatsev** [comment]
Sorry, haven't had a chance to test it yet.

**Review by gkatsev — APPROVED** [review]
Finally got around to this. Confirmed that this does what's expected.

I also found a test source with a labeled text track https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel-hoh-subs.ism/.mpd (though, VHS won't be able to play it, since VHS doesn't support IMSC currently).

**Review by misteroneill — APPROVED** [review]

**Pull request merged**
